// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB21-wG0bhpTY3sSFQ1KFPM9ttmx7OUEvc',
    appId: '1:613392160520:web:0ff605f61ed33f1aa07ebd',
    messagingSenderId: '613392160520',
    projectId: 'chat-app-dcacf',
    authDomain: 'chat-app-dcacf.firebaseapp.com',
    storageBucket: 'chat-app-dcacf.firebasestorage.app',
    measurementId: 'G-SS0ZGGNG9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6PYktdfuaFfhAD3rKZLSDItgK78SgTP0',
    appId: '1:613392160520:android:d3cc45edaaa156faa07ebd',
    messagingSenderId: '613392160520',
    projectId: 'chat-app-dcacf',
    storageBucket: 'chat-app-dcacf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm5UjA0wob1fXNVy8DH3p0jEnTi_pu9FQ',
    appId: '1:613392160520:ios:1b15856d66ae735fa07ebd',
    messagingSenderId: '613392160520',
    projectId: 'chat-app-dcacf',
    storageBucket: 'chat-app-dcacf.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm5UjA0wob1fXNVy8DH3p0jEnTi_pu9FQ',
    appId: '1:613392160520:ios:1b15856d66ae735fa07ebd',
    messagingSenderId: '613392160520',
    projectId: 'chat-app-dcacf',
    storageBucket: 'chat-app-dcacf.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB21-wG0bhpTY3sSFQ1KFPM9ttmx7OUEvc',
    appId: '1:613392160520:web:2103d628be75d397a07ebd',
    messagingSenderId: '613392160520',
    projectId: 'chat-app-dcacf',
    authDomain: 'chat-app-dcacf.firebaseapp.com',
    storageBucket: 'chat-app-dcacf.firebasestorage.app',
    measurementId: 'G-JE5QXSHZG6',
  );
}
